### ISSUE TITLE
Extra month detail before system dateformat: "October 26.10.2015 11:30" 

### ISSUE THREAD

**Issue by markosu** [getgrav/grav-theme-twentyfifteen#4]
There is bug on showing date below blog text (extra month detail).

In system.yaml:
```
 dateformat:
    default: 'd.m.Y H:i'
    short: 'd.m.y G:i'
    long: 'd.m.y G:i'
```

Screenshot:
![twentyfifteen_issue_dateformat-2015-11](https://cloud.githubusercontent.com/assets/6770959/11118947/ad41cdde-894e-11e5-8646-4381c3b5a52e.png)
